# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Recursos de aprendizaje', url: 'resources'}
- {name: 'Publicaciones',           url: 'posts'}
- {name: 'Documentación',           url: 'documentation'}
- {name: '¿Quiénes Somos?',         url: 'about'}
- {name: 'Contacto',                url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link:    'https://www.linkedin.com/in/oreyes/'}
#- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
#- {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Post Nuevos'
  previous_page: 'Post Antiguos'

sharing_button_prompt: 'Compartir!'

related_posts: 'También te podría interesar...'

post_date_prefix: 'Escrito en'
